#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
WIN_HOME=/mnt/c/Users/${USER^}

# remove any previous directories or files
# create the symlink
# ln -s $DOTFILES/nvim to (destination directory eg. $HOME/.config/nvim)

# INFO: WSL

unlink $HOME/.bash_aliases
ln -s $DOTFILES/bash/aliases.sh $HOME/.bash_aliases

unlink $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

unlink $HOME/.config/git
ln -s $DOTFILES/.config/git $HOME/.config/git

unlink $HOME/.config/lazygit
ln -s $DOTFILES/.config/lazygit $HOME/.config/lazygit

unlink $HOME/.config/opencode/opencode.json
ln -s $DOTFILES/.config/opencode/opencode.json $HOME/.config/opencode/opencode.json

# INFO: Windows

rm -f $MY_WIN_HOME/.config/wezterm/wezterm.lua $WIN_HOME/.config/wezterm/my_keys.lua
cp -r $DOTFILES/wezterm/ $WIN_HOME/.config/

cp $DOTFILES/.config/git/.gitignore $WIN_HOME/.gitignore

# rm -rf $HOME/.config/phpactor
# ln -s $DOTFILES/phpactor $HOME/.config/phpactor

