#!/usr/bin/env bash

DOTFILES=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)

# remove any previous directories or files
# create the symlink
# ln -s $DOTFILES/nvim to (destination directory eg. $HOME/.config/nvim)

rm -rf $HOME/.config/zellij
ln -s $DOTFILES/zellij $HOME/.config/zellij

rm -rf $HOME/.config/nvim
ln -s $DOTFILES/nvim $HOME/.config/nvim

rm -r $HOME/.gitconfig $HOME/.gitignore
ln -s $DOTFILES/git/.gitconfig $HOME/.gitconfig
ln -s $DOTFILES/git/.gitignore $HOME/.gitignore

rm $HOME/.config/lazygit/config.yml
ln -s $DOTFILES/lazygit/config.yml $HOME/.config/lazygit/config.yml

rm -f /mnt/c/Users/Mario/.wezterm.lua
cp ./wezterm/.wezterm.lua /mnt/c/Users/Mario/.wezterm.lua

# rm -rf $HOME/.config/phpactor
# ln -s $DOTFILES/phpactor $HOME/.config/phpactor

